config/routes.rb
Rails.application.routes.draw do
  resources :homes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.require(:home).permit(:index)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home) do |form| %>
  <% if home.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
        <% home.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.text_field :index %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
  <p>
    <strong>Index:</strong>
    <%= home.index %>
  </p>

</div>

app/views/homes/edit.html.erb
<h1>Editing home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Show this home", @home %> |
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Homes</h1>

<div id="homes">
  <% @homes.each do |home| %>
    <%= render home %>
    <p>
      <%= link_to "Show this home", home %>
    </p>
  <% end %>
</div>

<%= link_to "New home", new_home_path %>

app/views/homes/new.html.erb
<h1>New home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @home %>

<div>
  <%= link_to "Edit this home", edit_home_path(@home) %> |
  <%= link_to "Back to homes", homes_path %>

  <%= button_to "Destroy this home", @home, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>